version: "3.8"

services:
  ticketing-ticket-ticket:
    build:
      context: ./Backend
      dockerfile: ./Dockerfiles/Dockerfile.ticket
    ports:
      - "5003:80"
    env_file:
      - ./Configuration/authentication.env
      - ./Configuration/ticket.env
      - ./Configuration/brokerConfigurations.env
    environment:
      - RunningInDocker=true
      - RepositoryConnection=Data Source=/app/db.db
      - RabbitMQConnection=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - ticketing-micro-net
  ticketing-ticket-auth:
    build:
      context: ./Backend
      dockerfile: ./Dockerfiles/Dockerfile.auth
    ports:
      - "5001:80"
    env_file:
      - ./Configuration/authentication.env
      - ./Configuration/auth.env  
    environment:
      - RunningInDocker=true
      - RepositoryConnection=Data Source=/app/db.db
    networks:
      - ticketing-micro-net
  ticketing-ticket-user:
    build:
      context: ./Backend
      dockerfile: ./Dockerfiles/Dockerfile.user
    ports:
      - "5002:80"
    env_file:
      - ./Configuration/authentication.env
      - ./Configuration/user.env  
    environment:
      - RunningInDocker=true
      - RepositoryConnection=Data Source=/app/db.db
    networks:
      - ticketing-micro-net
  ticketing-ticket-bff:
    build:
      context: ./Backend
      dockerfile: ./Dockerfiles/Dockerfile.bff
    ports:
      - "5000:80"
    env_file:
      - ./Configuration/authentication.env
      - ./Configuration/bff.env  
    environment:
      - RunningInDocker=true  
      - AuthClientUrl=http://ticketing-ticket-auth/,
      - UserClientUrl=http://ticketing-ticket-user/,
      - TicketClientUrl=http://ticketing-ticket-ticket/
    depends_on:
      - ticketing-ticket-user
      - ticketing-ticket-auth
      - ticketing-ticket-ticket
    networks:
      - ticketing-micro-net
  ticketing-ticket-notifications:
    build:
      context: ./Backend
      dockerfile: ./Dockerfiles/Dockerfile.notifications
    ports:
      - "5004:80"
    env_file:
      - ./Configuration/authentication.env
      - ./Configuration/notifications.env
      - ./Configuration/brokerConfigurations.env
    environment:
      - RunningInDocker=true 
      - RepositoryConnection=Data Source=/app/db.db
      - RabbitMQConnection=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - ticketing-micro-net
  
  ticketing-frontend:
    build:
      context: ./Frontend/Ticketing
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - ticketing-ticket-bff
    networks:
      - ticketing-micro-net

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ticketing-micro-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ticketing-micro-net
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  ticketing-micro-net:
    name: ticketing-micro-net
    driver: bridge
