version: "3.8"

services:
  ticketing-ticket-ticket:
    build:
      context: ./Backend
      dockerfile: Dockerfile.ticket
    ports:
      - "5003:80"
    environment:
      - RepositoryConnection=Data Source=/app/Ticket.db
      
      # Authentication config
      - Secret=jEDkl97XMZP3j78qLJd9Kbnw6V2Hr0G1YpsR4Q8fzUKsXw2BpVIYzAC4Wt5Fn1u
      - Issuer=ticketing-auth
      - Audience=ticketing-app

      # OpenTelemetry config
      - PropertiesToTrace=Id
      - TraceContents=false
      - ServiceName=TicketService
      - ExcludedPaths=swagger,health
      - AgentHost=zipkin
      - AgentPort=9411

      # Logging config
      - MinimumLevel=Verbose
      - Sink=Console
      - FilePath=Logs/TicketService.log

      - ASPNETCORE_ENVIRONMENT=development 
    networks:
      - ticketing-micro-net
  ticketing-ticket-auth:
    build:
      context: ./Backend
      dockerfile: Dockerfile.auth
    ports:
      - "5001:80"
    environment:
      - RepositoryConnection=Data Source=/app/Auth.db

      # Authentication config
      - Secret=jEDkl97XMZP3j78qLJd9Kbnw6V2Hr0G1YpsR4Q8fzUKsXw2BpVIYzAC4Wt5Fn1u
      - Issuer=ticketing-auth
      - Audience=ticketing-app

      # OpenTelemetry config
      - PropertiesToTrace=Id
      - TraceContents=false
      - ServiceName=AuthService
      - ExcludedPaths=swagger,health
      - AgentHost=zipkin
      - AgentPort=9411

      # Logging config
      - MinimumLevel=Verbose
      - Sink=Console
      - FilePath=Logs/AuthService.log

      - ASPNETCORE_ENVIRONMENT=development 
    networks:
      - ticketing-micro-net
  ticketing-ticket-user:
    build:
      context: ./Backend
      dockerfile: Dockerfile.user
    ports:
      - "5002:80"
    environment:
      - RepositoryConnection=Data Source=/app/User.db

      # Authentication config
      - Secret=jEDkl97XMZP3j78qLJd9Kbnw6V2Hr0G1YpsR4Q8fzUKsXw2BpVIYzAC4Wt5Fn1u
      - Issuer=ticketing-auth
      - Audience=ticketing-app

      # OpenTelemetry config
      - PropertiesToTrace=Id
      - TraceContents=false
      - ServiceName=UserService
      - ExcludedPaths=swagger,health
      - AgentHost=zipkin
      - AgentPort=9411

      # Logging config
      - MinimumLevel=Verbose
      - Sink=Console
      - FilePath=Logs/UserService.log

      - ASPNETCORE_ENVIRONMENT=development 
    networks:
      - ticketing-micro-net
  ticketing-ticket-bff:
    build:
      context: ./Backend
      dockerfile: Dockerfile.bff
    ports:
      - "5000:80"
    environment:
      # Authentication config
      - Secret=jEDkl97XMZP3j78qLJd9Kbnw6V2Hr0G1YpsR4Q8fzUKsXw2BpVIYzAC4Wt5Fn1u
      - Issuer=ticketing-auth
      - Audience=ticketing-app

      # OpenTelemetry config
      - PropertiesToTrace=Id
      - TraceContents=false
      - ServiceName=BffService
      - ExcludedPaths=swagger,health
      - AgentHost=zipkin
      - AgentPort=9411

      # Logging config
      - MinimumLevel=Verbose
      - Sink=Console
      - FilePath=Logs/BffService.log

      # Client config
      - AuthClientUrl=http://ticketing-ticket-auth/,
      - UserClientUrl=http://ticketing-ticket-user/,
      - TicketClientUrl=http://ticketing-ticket-ticket/

      - ASPNETCORE_ENVIRONMENT=development 
    depends_on:
      - ticketing-ticket-user
      - ticketing-ticket-auth
      - ticketing-ticket-ticket
    networks:
      - ticketing-micro-net
  
  ticketing-frontend:
    build:
      context: ./Frontend/Ticketing
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - ticketing-ticket-bff
    networks:
      - ticketing-micro-net

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ticketing-micro-net

networks:
  ticketing-micro-net:
    name: ticketing-micro-net
    driver: bridge
