version: "3.8"

services:
  ticketing-api:
    build:
      context: ./Backend/src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - SerilogMinimumLevel=Debug
      - ASPNETCORE_ENVIRONMENT=integration
      - RepositoryConnection=Data Source=/app/Ticketing.db
    networks:
      - ticketing-micro-net

  ticketing-frontend:
    build:
      context: ./Frontend/Ticketing
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - ticketing-api
    networks:
      - ticketing-micro-net

networks:
  ticketing-micro-net:
    name: ticketing-micro-net
    driver: bridge
