version: "3.8"

services:
  ticketing-ticket-ticket:
    build:
      context: ./Backend
      dockerfile: Dockerfile.ticket
    ports:
      - "5003:80"
    env_file:
      - ticket.env  
    networks:
      - ticketing-micro-net
  ticketing-ticket-auth:
    build:
      context: ./Backend
      dockerfile: Dockerfile.auth
    ports:
      - "5001:80"
    env_file:
      - auth.env  
    networks:
      - ticketing-micro-net
  ticketing-ticket-user:
    build:
      context: ./Backend
      dockerfile: Dockerfile.user
    ports:
      - "5002:80"
    env_file:
      - user.env  
    networks:
      - ticketing-micro-net
  ticketing-ticket-bff:
    build:
      context: ./Backend
      dockerfile: Dockerfile.bff
    ports:
      - "5000:80"
    env_file:
      - bff.env    
    depends_on:
      - ticketing-ticket-user
      - ticketing-ticket-auth
      - ticketing-ticket-ticket
    networks:
      - ticketing-micro-net
  
  ticketing-frontend:
    build:
      context: ./Frontend/Ticketing
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - ticketing-ticket-bff
    networks:
      - ticketing-micro-net

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ticketing-micro-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ticketing-micro-net
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  ticketing-micro-net:
    name: ticketing-micro-net
    driver: bridge
